'''
Write the parasite table of the paper from config.yml: every parasite with its
taxonomic group, niche, hosts and lifecycle tissues, next to how many
interactions the pipeline predicts for it. Organisation is left out: the
helminth groups are multicellular and the rest unicellular, which the caption
says. Three renderings of the same rows go to paper/tables/:
parasites.tex is \input by paper.tex, parasites.csv opens in Google Sheets, and
parasites.html pastes into Google Docs as a table when opened in a browser and
copied.
'''
import argparse
import html
import os
import sys

import pandas as pd

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import utils

COLUMNS = ['Species', 'Group', 'Niche', 'Hosts', 'Tissues', 'Predicted PPIs']


def build_rows(config_file, data_dir):
    parasites = utils.read_config(filepath=config_file, field='parasites')
    hosts = utils.read_config(filepath=config_file, field='hosts')
    tissues = utils.read_config(filepath=config_file, field='tissues')
    # config.yml lists the groups helminths first, then protozoa: rows follow it.
    group_order = list(utils.read_config(filepath=config_file, field='parasite_groups'))
    predictions = pd.read_parquet(os.path.join(data_dir, 'predictions.parquet'))
    counts = predictions.groupby(predictions['taxid1'].astype(int)).size()

    # The common name in parentheses is enough to identify a host here.
    host_names = {taxid: host['label'].split('(')[1].rstrip(')')
                  for taxid, host in hosts.items()}
    rows = []
    def order(item):
        parasite = item[1]
        return group_order.index(parasite['group']), parasite['label']

    for taxid, parasite in sorted(parasites.items(), key=order):
        rows.append({
            'Species': parasite['label'],
            'Group': parasite['group'],
            'Niche': parasite['niche'],
            'Hosts': ', '.join(host_names[host] for host in parasite['hosts']),
            'Tissues': ', '.join(tissues[bto] for bto in parasite['tissues']),
            'Predicted PPIs': int(counts.get(taxid, 0)),
        })
    return pd.DataFrame(rows, columns=COLUMNS)


def write_tex(table, path):
    def cell(value):
        return str(value).replace('&', r'\&').replace('%', r'\%')

    lines = [
        '% Generated by scripts/build_parasite_table.py -- do not edit by hand.',
        # Narrower margins on the table's own page keep all 45 rows on it.
        r'\newgeometry{margin=1.5cm}',
        r'\begin{landscape}',
        # \singlespacing first: it resets the stretch, so the font size that
        # follows sets the row height.
        r'\singlespacing\scriptsize',
        r'\setlength{\LTcapwidth}{\textwidth}',
        r'\rowcolors{2}{rowblue}{white}',
        r'\begin{longtable}{@{}L{4.2cm}L{2.4cm}L{2.1cm}L{3cm}L{8.4cm}r@{}}',
        r'\caption{Parasites included in OrthoHPI 2.0. Nematoda, Trematoda and'
        r' Cestoda are multicellular, the other groups unicellular; tissues are'
        r' those the parasite occupies in the host during its lifecycle.'
        r' Predicted PPIs are the interactions of the final network.}'
        r'\label{tab:parasites}\\',
        r'\toprule',
        ' & '.join(COLUMNS) + r'\\',
        r'\midrule',
        r'\endfirsthead',
        r'\multicolumn{6}{@{}l}{\textit{Table~\ref{tab:parasites} continued}}\\',
        r'\toprule',
        ' & '.join(COLUMNS) + r'\\',
        r'\midrule',
        r'\endhead',
        r'\midrule',
        r'\multicolumn{6}{r@{}}{\textit{continued on next page}}\\',
        r'\endfoot',
        r'\bottomrule',
        r'\endlastfoot',
    ]
    for _, row in table.iterrows():
        values = [r'\textit{' + cell(row['Species']) + '}']
        values += [cell(row[column]) for column in COLUMNS[1:5]]
        values += [r'\num{' + str(row[column]) + '}' for column in COLUMNS[5:]]
        lines.append(' & '.join(values) + r'\\')
    lines += [r'\end{longtable}', r'\end{landscape}', r'\restoregeometry', '']
    with open(path, 'w') as handle:
        handle.write('\n'.join(lines))


def write_html(table, path):
    lines = ['<table border="1" style="border-collapse:collapse;font-family:Arial;font-size:10pt">',
             '<tr>' + ''.join(f'<th>{c}</th>' for c in COLUMNS) + '</tr>']
    for i, (_, row) in enumerate(table.iterrows()):
        cells = [f'<td><i>{html.escape(row["Species"])}</i></td>']
        cells += [f'<td>{html.escape(str(row[c]))}</td>' for c in COLUMNS[1:5]]
        cells += [f'<td style="text-align:right">{row[c]:,}</td>' for c in COLUMNS[5:]]
        style = ' style="background:#e8f1fb"' if i % 2 == 0 else ''
        lines.append(f'<tr{style}>' + ''.join(cells) + '</tr>')
    lines += ['</table>', '']
    with open(path, 'w') as handle:
        handle.write('\n'.join(lines))


def build(config_file, data_dir, out_dir):
    table = build_rows(config_file, data_dir)
    os.makedirs(out_dir, exist_ok=True)
    table.to_csv(os.path.join(out_dir, 'parasites.csv'), index=False)
    write_tex(table, os.path.join(out_dir, 'parasites.tex'))
    write_html(table, os.path.join(out_dir, 'parasites.html'))
    print(f"Wrote {out_dir}/parasites.{{tex,csv,html}}: {len(table)} parasites, "
          f"{table['Predicted PPIs'].sum():,} predicted PPIs")


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('--config', default='config.yml', help='configuration file to read')
    parser.add_argument('--data-dir', default='data', help='directory holding the parquet files')
    parser.add_argument('--out-dir', default='paper/tables', help='directory to write into')
    args = parser.parse_args()

    build(config_file=args.config, data_dir=args.data_dir, out_dir=args.out_dir)
