'''
Write the parasite table of the paper from config.yml: every parasite with its
organisation (U/M), niche (I/E), hosts and lifecycle tissues. Rows follow the
taxonomic group order of config.yml. Three renderings of the same rows go to
paper/tables/: parasites.tex is \input by paper.tex, parasites.csv opens in
Google Sheets, and parasites.html pastes into Google Docs as a table when
opened in a browser and copied.
'''
import argparse
import html
import os
import sys

import pandas as pd

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import utils

COLUMNS = ['Species', 'U/M', 'I/E', 'Hosts', 'Tissues']
TEXT_COLUMNS = COLUMNS[1:]


def build_rows(config_file):
    parasites = utils.read_config(filepath=config_file, field='parasites')
    hosts = utils.read_config(filepath=config_file, field='hosts')
    tissues = utils.read_config(filepath=config_file, field='tissues')
    # config.yml lists the groups helminths first, then protozoa: rows follow it.
    group_order = list(utils.read_config(filepath=config_file, field='parasite_groups'))

    # The common name in parentheses is enough to identify a host here.
    host_names = {taxid: host['label'].split('(')[1].rstrip(')')
                  for taxid, host in hosts.items()}
    rows = []
    def order(item):
        parasite = item[1]
        return group_order.index(parasite['group']), parasite['label']

    for taxid, parasite in sorted(parasites.items(), key=order):
        rows.append({
            'Species': parasite['label'],
            'U/M': 'M' if parasite.get('multicellular') else 'U',
            'I/E': parasite['niche'][0].upper(),
            'Hosts': ', '.join(host_names[host] for host in parasite['hosts']),
            'Tissues': ', '.join(tissues[bto] for bto in parasite['tissues']),
        })
    return pd.DataFrame(rows, columns=COLUMNS)


def write_tex(table, path):
    def cell(value):
        return str(value).replace('&', r'\&').replace('%', r'\%')

    width = len(COLUMNS)
    lines = [
        '% Generated by scripts/build_parasite_table.py -- do not edit by hand.',
        # Every row fits on one page, so the table starts on a fresh one.
        r'\clearpage',
        # \singlespacing first: it resets the stretch, so the font size that
        # follows sets the row height.
        r'\singlespacing\scriptsize',
        r'\setlength{\LTcapwidth}{\textwidth}',
        r'\rowcolors{2}{rowblue}{white}',
        # The widths add up to the 180 mm text block, so the table sits
        # upright on the page, and each is a little wider than its widest
        # entry, so that no cell wraps.
        r'\begin{longtable}{@{}L{3.95cm}cc L{2.6cm}L{8.6cm}@{}}',
        r'\caption{Parasites included in OrthoHPI 2.0, ordered by taxonomic'
        r' group. U/M: unicellular or multicellular; I/E: intracellular or'
        r' extracellular niche in the host; tissues are those the parasite'
        r' occupies in the host during its lifecycle.}'
        r'\label{tab:parasites}\\',
        r'\toprule',
        ' & '.join(COLUMNS) + r'\\',
        r'\midrule',
        r'\endfirsthead',
        rf'\multicolumn{{{width}}}{{@{{}}l}}{{\textit{{Table~\ref{{tab:parasites}} continued}}}}\\',
        r'\toprule',
        ' & '.join(COLUMNS) + r'\\',
        r'\midrule',
        r'\endhead',
        r'\midrule',
        rf'\multicolumn{{{width}}}{{r@{{}}}}{{\textit{{continued on next page}}}}\\',
        r'\endfoot',
        r'\bottomrule',
        r'\endlastfoot',
    ]
    for _, row in table.iterrows():
        values = [r'\textit{' + cell(row['Species']) + '}']
        values += [cell(row[column]) for column in TEXT_COLUMNS]
        lines.append(' & '.join(values) + r'\\')
    lines += [r'\end{longtable}', '']
    with open(path, 'w') as handle:
        handle.write('\n'.join(lines))


def write_html(table, path):
    lines = ['<table border="1" style="border-collapse:collapse;font-family:Arial;font-size:10pt">',
             '<tr>' + ''.join(f'<th>{c}</th>' for c in COLUMNS) + '</tr>']
    for i, (_, row) in enumerate(table.iterrows()):
        cells = [f'<td><i>{html.escape(row["Species"])}</i></td>']
        cells += [f'<td>{html.escape(str(row[c]))}</td>' for c in TEXT_COLUMNS]
        style = ' style="background:#e8f1fb"' if i % 2 == 0 else ''
        lines.append(f'<tr{style}>' + ''.join(cells) + '</tr>')
    lines += ['</table>', '']
    with open(path, 'w') as handle:
        handle.write('\n'.join(lines))


def build(config_file, out_dir):
    table = build_rows(config_file)
    os.makedirs(out_dir, exist_ok=True)
    table.to_csv(os.path.join(out_dir, 'parasites.csv'), index=False)
    write_tex(table, os.path.join(out_dir, 'parasites.tex'))
    write_html(table, os.path.join(out_dir, 'parasites.html'))
    print(f"Wrote {out_dir}/parasites.{{tex,csv,html}}: {len(table)} parasites")


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('--config', default='config.yml', help='configuration file to read')
    parser.add_argument('--out-dir', default='paper/tables', help='directory to write into')
    args = parser.parse_args()

    build(config_file=args.config, out_dir=args.out_dir)
